name: Base image 

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
    branches:
      - main
      - 'feature/**'

jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      -
        name: Code | Checkout
        uses: actions/checkout@v3
  Baking:
    secrets: inherit
    uses: mammdoo/actions-reusable-workflow/.github/workflow/scaffold-base-image.yml@main
    needs: [Checkout]
